"""v3 initial schema

Revision ID: d3b41e470e35
Revises: 
Create Date: 2026-10-08 15:33:14.686407

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = 'd3b41e470e35'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus'), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_table('settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('shortcuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('static', 'dynamic', 'user-dynamic', name='shortcuttype'), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'unlisted', 'private', 'team', name='visibility'), nullable=True),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortcuts_expires_at'), 'shortcuts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shortcuts_owner_email'), 'shortcuts', ['owner_email'], unique=False)
    op.create_index(op.f('ix_shortcuts_pattern'), 'shortcuts', ['pattern'], unique=True)
    op.create_table('upstream_cache',
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upstream_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pattern', 'upstream_name')
    )
    op.create_index(op.f('ix_upstream_cache_upstream_name'), 'upstream_cache', ['upstream_name'], unique=False)
    op.create_table('upstream_check_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upstream_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tried_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern', 'upstream_name', name='uq_pattern_upstream')
    )
    op.create_index(op.f('ix_upstream_check_log_pattern'), 'upstream_check_log', ['pattern'], unique=False)
    op.create_index(op.f('ix_upstream_check_log_upstream_name'), 'upstream_check_log', ['upstream_name'], unique=False)
    op.create_table('upstreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fail_status_code', sa.Integer(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('skip_sso_cache', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upstreams_name'), 'upstreams', ['name'], unique=True)
    op.create_table('user_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcut_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('param_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut_pattern', 'param_name', name='uq_shortcut_param')
    )
    op.create_index(op.f('ix_user_params_shortcut_pattern'), 'user_params', ['shortcut_pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_params_shortcut_pattern'), table_name='user_params')
    op.drop_table('user_params')
    op.drop_index(op.f('ix_upstreams_name'), table_name='upstreams')
    op.drop_table('upstreams')
    op.drop_index(op.f('ix_upstream_check_log_upstream_name'), table_name='upstream_check_log')
    op.drop_index(op.f('ix_upstream_check_log_pattern'), table_name='upstream_check_log')
    op.drop_table('upstream_check_log')
    op.drop_index(op.f('ix_upstream_cache_upstream_name'), table_name='upstream_cache')
    op.drop_table('upstream_cache')
    op.drop_index(op.f('ix_shortcuts_pattern'), table_name='shortcuts')
    op.drop_index(op.f('ix_shortcuts_owner_email'), table_name='shortcuts')
    op.drop_index(op.f('ix_shortcuts_expires_at'), table_name='shortcuts')
    op.drop_table('shortcuts')
    op.drop_table('settings')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
