/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List backups */
        get: operations["list_backup_archives_api_v1_admin_backup_get"];
        put?: never;
        /** Enqueue a backup job */
        post: operations["create_backup_job_api_v1_admin_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backup/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a backup archive */
        get: operations["download_backup_api_v1_admin_backup__name__get"];
        put?: never;
        post?: never;
        /** Delete a backup */
        delete: operations["delete_backup_api_v1_admin_backup__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backup/{name}:restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a restore job */
        post: operations["restore_backup_job_api_v1_admin_backup__name__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system configuration
         * @description Return active system configuration, editable schema, and stored settings.
         */
        get: operations["get_config_api_v1_admin_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update system settings
         * @description Update settings entries in the database.
         *
         *     Known editable keys are validated + coerced (422 otherwise); anything
         *     else is stored verbatim under `custom` for import fidelity.
         */
        patch: operations["update_config_api_v1_admin_config_patch"];
        trace?: never;
    };
    "/api/v1/auth/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description List keys (never secret material — only prefixes).
         */
        get: operations["list_api_keys_api_v1_auth_api_keys_get"];
        put?: never;
        /**
         * Issue an API key
         * @description Mint a key for automation. The plaintext is returned exactly once.
         */
        post: operations["issue_api_key_api_v1_auth_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revoke_api_key_api_v1_auth_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description Authenticate admin password: JWT immediately, or an MFA challenge
         *     (exchange at `mfa/verify`) when TOTP is enrolled.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current admin
         * @description Return currently authenticated identity.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/backup-codes:regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate backup codes
         * @description Mint a fresh backup-code set (old codes die) with TOTP possession proof.
         */
        post: operations["mfa_regenerate_codes_api_v1_auth_mfa_backup_codes_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable MFA
         * @description Disable MFA with TOTP proof of possession; clears seed and codes.
         */
        post: operations["mfa_disable_api_v1_auth_mfa_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable TOTP
         * @description Verify a token from the staged seed: enables MFA and mints single-use
         *     backup codes (plaintext exactly once — store them now).
         */
        post: operations["mfa_enable_api_v1_auth_mfa_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start TOTP enrollment
         * @description Stage a fresh seed (render the URL as QR). Nothing is enabled until
         *     a token from the new seed verifies at `mfa/enable`.
         */
        post: operations["mfa_setup_api_v1_auth_mfa_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MFA enrollment status */
        get: operations["mfa_status_api_v1_auth_mfa_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete MFA login
         * @description Exchange a pending login token + TOTP (or one unused backup code,
         *     consumed on use) for a full JWT.
         */
        post: operations["mfa_verify_api_v1_auth_mfa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Enqueue a background job */
        post: operations["enqueue_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel a queued/running job */
        delete: operations["cancel_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream job progress via SSE */
        get: operations["stream_job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated KPI metrics
         * @description Return aggregated KPI metrics (totals, breakdowns, top tags, popularity).
         */
        get: operations["get_kpi_metrics_api_v1_metrics_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live process telemetry
         * @description Return process runtime telemetry and live counter snapshots.
         */
        get: operations["get_live_metrics_api_v1_metrics_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate QR code as JSON base64
         * @description Return base64-encoded PNG and URL metadata.
         */
        get: operations["get_qr_json_api_v1_qr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a subpath (debug) */
        get: operations["api_resolve_api_v1_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortcuts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shortcuts */
        get: operations["list_shortcuts_api_v1_shortcuts_get"];
        put?: never;
        /** Create shortcut */
        post: operations["create_shortcut_api_v1_shortcuts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortcuts/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk delete shortcuts */
        post: operations["bulk_delete_shortcuts_api_v1_shortcuts_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortcuts/bulk-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import shortcuts
         * @description Upsert shortcuts by pattern (insert new, overwrite existing). Invalid
         *     rows are skipped, never fatal — the response reports every outcome.
         */
        post: operations["bulk_import_shortcuts_api_v1_shortcuts_bulk_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortcuts/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shortcut details */
        get: operations["get_shortcut_api_v1_shortcuts__pattern__get"];
        put?: never;
        post?: never;
        /** Delete shortcut */
        delete: operations["delete_shortcut_api_v1_shortcuts__pattern__delete"];
        options?: never;
        head?: never;
        /** Update shortcut */
        patch: operations["update_shortcut_api_v1_shortcuts__pattern__patch"];
        trace?: never;
    };
    "/api/v1/site/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public action policy
         * @description Which mutating actions are open to anonymous clients (admin-curated).
         */
        get: operations["site_policy_api_v1_site_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all upstreams */
        get: operations["list_upstreams_api_v1_upstreams_get"];
        put?: never;
        /** Create an upstream */
        post: operations["create_upstream_api_v1_upstreams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cached upstream shortcuts */
        get: operations["list_upstream_cache_api_v1_upstreams_cache_get"];
        put?: never;
        post?: never;
        /** Purge upstream shortcut cache */
        delete: operations["purge_upstream_cache_api_v1_upstreams_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/cache/resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resync upstream cache
         * @description Re-check one pattern (or all cached ones) and reconcile cache rows.
         *
         *     Synchronous by design at this scale; graduate to arq workers (EPIC-04/06)
         *     if resync-all outgrows the 3 s-per-check request budget.
         */
        post: operations["resync_upstream_cache_api_v1_upstreams_cache_resync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/cache/{upstream}/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Purge one cached upstream entry */
        delete: operations["purge_cache_entry_api_v1_upstreams_cache__upstream___pattern__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/check-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upstream check logs */
        get: operations["list_check_logs_api_v1_upstreams_check_logs_get"];
        put?: never;
        post?: never;
        /** Clear upstream check logs */
        delete: operations["clear_check_logs_api_v1_upstreams_check_logs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/check/stream/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream real-time upstream resolution check via SSE */
        get: operations["stream_upstream_check_api_v1_upstreams_check_stream__pattern__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams/{upstream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an upstream */
        delete: operations["delete_upstream_api_v1_upstreams__upstream_id__delete"];
        options?: never;
        head?: never;
        /** Update an upstream */
        patch: operations["update_upstream_api_v1_upstreams__upstream_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (alias) */
        get: operations["healthz_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qr/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate QR code PNG image
         * @description Return raw PNG binary for the shortcut QR code.
         */
        get: operations["get_qr_image_qr__pattern__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{pattern}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve and redirect a shortcut */
        get: operations["redirect_shortcut__pattern__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /**
             * Name
             * @description Human label, e.g. 'nightly import cron'
             */
            name: string;
            /**
             * Scopes
             * @description Recorded now, enforced by the RBAC audit (EPIC-05 task 3)
             */
            scopes?: string[];
        };
        /**
         * ApiKeyIssued
         * @description Issuance response — carries the plaintext key exactly once.
         */
        ApiKeyIssued: {
            /** Api Key */
            api_key: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Last Used At */
            last_used_at?: string | null;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Revoked At */
            revoked_at?: string | null;
            /**
             * Scopes
             * @default []
             */
            scopes: string[];
        };
        /** ApiKeyRead */
        ApiKeyRead: {
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Last Used At */
            last_used_at?: string | null;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Revoked At */
            revoked_at?: string | null;
            /**
             * Scopes
             * @default []
             */
            scopes: string[];
        };
        /** BackupCreate */
        BackupCreate: {
            /**
             * Label
             * @description Optional filename tag, [a-z0-9-] max 32 chars
             */
            label?: string | null;
        };
        /** BackupDeleteResponse */
        BackupDeleteResponse: {
            /** Name */
            name: string;
            /** Success */
            success: boolean;
        };
        /** BackupEnqueue */
        BackupEnqueue: {
            /**
             * Kind
             * @description Job kind to run
             * @constant
             */
            kind: "backup_create";
            /**
             * Label
             * @description Optional filename tag
             */
            label?: string | null;
        };
        /** BackupRead */
        BackupRead: {
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Tables */
            tables: {
                [key: string]: number;
            };
        };
        /** BackupRestoreEnqueue */
        BackupRestoreEnqueue: {
            /**
             * Kind
             * @description Job kind to run
             * @constant
             */
            kind: "backup_restore";
            /**
             * Name
             * @description Archive name to restore
             */
            name: string;
        };
        /** BulkDeleteRequest */
        BulkDeleteRequest: {
            /** Patterns */
            patterns: string[];
        };
        /** BulkDeleteResponse */
        BulkDeleteResponse: {
            /** Count */
            count: number;
            /** Deleted */
            deleted: string[];
            /** Not Found */
            not_found: string[];
        };
        /** BulkImportRequest */
        BulkImportRequest: {
            /** Shortcuts */
            shortcuts: components["schemas"]["ShortcutCreate"][];
        };
        /** BulkImportResponse */
        BulkImportResponse: {
            /** Count */
            count: number;
            /** Inserted */
            inserted: number;
            /** Skipped */
            skipped: string[];
            /** Updated */
            updated: number;
        };
        /** ByType */
        ByType: {
            /** Hits */
            hits: number;
            /** Shortcuts */
            shortcuts: number;
            /** Type */
            type: string;
        };
        /** ByVisibility */
        ByVisibility: {
            /** Shortcuts */
            shortcuts: number;
            /** Visibility */
            visibility: string;
        };
        /** CachePurgeResult */
        CachePurgeResult: {
            /** Purged */
            purged: number;
            /** Success */
            success: boolean;
        };
        /** CacheResyncRequest */
        CacheResyncRequest: {
            /**
             * Pattern
             * @description Single pattern to refresh; omit to re-check all cached patterns
             */
            pattern?: string | null;
            /**
             * Upstream
             * @description Upstream name to resync against
             */
            upstream: string;
        };
        /** CacheResyncResponse */
        CacheResyncResponse: {
            /** Checked */
            checked: number;
            /** Cleared */
            cleared: number;
            /** Results */
            results: components["schemas"]["CacheResyncResult"][];
            /** Success */
            success: boolean;
            /** Updated */
            updated: number;
            /** Upstream */
            upstream: string;
        };
        /** CacheResyncResult */
        CacheResyncResult: {
            /**
             * Message
             * @default
             */
            message: string;
            /** Pattern */
            pattern: string;
            /** Resolved Url */
            resolved_url?: string | null;
            /** Status */
            status: string;
            /** Success */
            success: boolean;
        };
        /** CacheStats */
        CacheStats: {
            /** Hit Rate */
            hit_rate?: number | null;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
        };
        /** CheckLogEntry */
        CheckLogEntry: {
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Check Url */
            check_url?: string | null;
            /**
             * Count
             * @default 1
             */
            count: number;
            /** Detail */
            detail?: string | null;
            /** Id */
            id?: number | null;
            /** Pattern */
            pattern: string;
            /** Result */
            result?: string | null;
            /** Tried At */
            tried_at: string;
            /** Upstream Name */
            upstream_name: string;
        };
        /** ConfigUpdate */
        ConfigUpdate: {
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** Role */
            role: string;
            /** Sub */
            sub: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** HitBucket */
        HitBucket: {
            /** Bucket */
            bucket: string;
            /** Shortcuts */
            shortcuts: number;
        };
        /** JobRead */
        JobRead: {
            /**
             * Done
             * @default 0
             */
            done: number;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Result */
            result?: {
                [key: string]: {
                    [key: string]: unknown;
                } | unknown[] | string | number | boolean | null;
            } | null;
            /** Status */
            status: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** KpiBreakdowns */
        KpiBreakdowns: {
            /** By Type */
            by_type: components["schemas"]["ByType"][];
            /** By Visibility */
            by_visibility: components["schemas"]["ByVisibility"][];
            /** Hit Buckets */
            hit_buckets: components["schemas"]["HitBucket"][];
            /** Top Tags */
            top_tags: components["schemas"]["TopTag"][];
        };
        /** KpiOverview */
        KpiOverview: {
            /** Avg Hits */
            avg_hits: number;
            /** Created 30D */
            created_30d: number;
            /** Created 7D */
            created_7d: number;
            most_popular?: components["schemas"]["MostPopular"] | null;
            /** Total Hits */
            total_hits: number;
            /** Total Shortcuts */
            total_shortcuts: number;
            /** Zero Hit Count */
            zero_hit_count: number;
            /** Zero Hit Pct */
            zero_hit_pct: number;
        };
        /** KpiResponse */
        KpiResponse: {
            breakdowns: components["schemas"]["KpiBreakdowns"];
            overview: components["schemas"]["KpiOverview"];
            upstreams: components["schemas"]["UpstreamStats"];
        };
        /** LiveCounts */
        LiveCounts: {
            /** Total Hits */
            total_hits: number;
            /** Total Shortcuts */
            total_shortcuts: number;
        };
        /** LiveResponse */
        LiveResponse: {
            cache: components["schemas"]["CacheStats"];
            counts: components["schemas"]["LiveCounts"];
            process: components["schemas"]["ProcessInfo"];
            /** Status */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /**
         * MfaChallengeResponse
         * @description Challenged login: no JWT yet — exchange `pending_token` + TOTP at
         *     `POST /api/v1/auth/mfa/verify`.
         */
        MfaChallengeResponse: {
            /**
             * Mfa Required
             * @default true
             */
            mfa_required: boolean;
            /** Pending Token */
            pending_token: string;
        };
        /** MfaDisableRequest */
        MfaDisableRequest: {
            /**
             * Token
             * @description Current TOTP confirming the disable
             */
            token: string;
        };
        /** MfaEnableRequest */
        MfaEnableRequest: {
            /**
             * Token
             * @description Current 6-digit TOTP from the new seed
             */
            token: string;
        };
        /** MfaEnableResponse */
        MfaEnableResponse: {
            /**
             * Backup Codes
             * @description Single-use codes, plaintext exactly once — store them now
             */
            backup_codes: string[];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** MfaRegenerateRequest */
        MfaRegenerateRequest: {
            /**
             * Token
             * @description Current TOTP proving possession
             */
            token: string;
        };
        /**
         * MfaSetupResponse
         * @description Fresh TOTP seed: render `otpauth_url` as QR, keep `secret` for manual
         *     entry. Nothing is enabled until a token verifies (see enable).
         */
        MfaSetupResponse: {
            /** Otpauth Url */
            otpauth_url: string;
            /** Secret */
            secret: string;
        };
        /** MfaStatusResponse */
        MfaStatusResponse: {
            /** Backup Codes Remaining */
            backup_codes_remaining: number;
            /** Enabled */
            enabled: boolean;
        };
        /** MfaVerifyRequest */
        MfaVerifyRequest: {
            /**
             * Pending Token
             * @description Short-lived login token from a challenged login
             */
            pending_token: string;
            /**
             * Token
             * @description Current TOTP or one unused backup code
             */
            token: string;
        };
        /** MostPopular */
        MostPopular: {
            /** Hits */
            hits: number;
            /** Pattern */
            pattern: string;
            /** Target */
            target: string;
        };
        /** ProcessInfo */
        ProcessInfo: {
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Memory Mb */
            memory_mb?: number | null;
            /** Platform */
            platform: string;
            /** Python */
            python: string;
            /** Timestamp */
            timestamp: string;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
            /** Version */
            version: string;
        };
        /** QRCodeResponse */
        QRCodeResponse: {
            /** Pattern */
            pattern: string;
            /** Qr Base64 */
            qr_base64: string;
            /** Target Url */
            target_url: string;
        };
        /** Readiness */
        Readiness: {
            /** Data Dir Writable */
            data_dir_writable: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ShortcutCreate */
        ShortcutCreate: {
            /** Expires At */
            expires_at?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            /** Pattern */
            pattern: string;
            /** Tags */
            tags?: string[];
            /** Target */
            target: string;
            /** @default static */
            type: components["schemas"]["ShortcutType"];
            /** @default public */
            visibility: components["schemas"]["Visibility"];
        };
        /** ShortcutListMeta */
        ShortcutListMeta: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** ShortcutListResponse */
        ShortcutListResponse: {
            /** Data */
            data: components["schemas"]["ShortcutRead"][];
            meta: components["schemas"]["ShortcutListMeta"];
        };
        /** ShortcutRead */
        ShortcutRead: {
            /**
             * Access Count
             * @default 0
             */
            access_count: number;
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id?: number | null;
            /** Owner Email */
            owner_email?: string | null;
            /** Pattern */
            pattern: string;
            /** Tags */
            tags?: string[];
            /** Target */
            target: string;
            type: components["schemas"]["ShortcutType"];
            /** @default public */
            visibility: components["schemas"]["Visibility"];
        };
        /**
         * ShortcutType
         * @enum {string}
         */
        ShortcutType: "static" | "dynamic" | "user-dynamic";
        /** ShortcutUpdate */
        ShortcutUpdate: {
            /** Expires At */
            expires_at?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Target */
            target?: string | null;
            type?: components["schemas"]["ShortcutType"] | null;
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /** SitePolicy */
        SitePolicy: {
            /**
             * Known Actions
             * @default [
             *       "shortcuts.create",
             *       "upstreams.create"
             *     ]
             */
            known_actions: string[];
            /** Public Actions */
            public_actions: string[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Role */
            role: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopTag */
        TopTag: {
            /** Shortcuts */
            shortcuts: number;
            /** Tag */
            tag: string;
        };
        /** UpstreamCacheEntry */
        UpstreamCacheEntry: {
            /** Checked At */
            checked_at: string;
            /** Pattern */
            pattern: string;
            /** Resolved Url */
            resolved_url?: string | null;
            /** Upstream Name */
            upstream_name: string;
        };
        /** UpstreamCreate */
        UpstreamCreate: {
            /**
             * Base Url
             * @description Target base URL, e.g. https://go.dev
             */
            base_url: string;
            /**
             * Fail Status Code
             * @description Status code indicating missing shortcut
             */
            fail_status_code?: number | null;
            /**
             * Fail Url
             * @description URL returned by upstream on 404
             */
            fail_url?: string | null;
            /**
             * Name
             * @description Unique label for the upstream
             */
            name: string;
            /**
             * Skip Sso Cache
             * @description Never cache SSO target matches
             * @default false
             */
            skip_sso_cache: boolean;
            /**
             * Verify Ssl
             * @description Verify SSL certs
             * @default true
             */
            verify_ssl: boolean;
        };
        /** UpstreamRead */
        UpstreamRead: {
            /**
             * Base Url
             * @description Target base URL, e.g. https://go.dev
             */
            base_url: string;
            /**
             * Fail Status Code
             * @description Status code indicating missing shortcut
             */
            fail_status_code?: number | null;
            /**
             * Fail Url
             * @description URL returned by upstream on 404
             */
            fail_url?: string | null;
            /** Id */
            id?: number | null;
            /**
             * Name
             * @description Unique label for the upstream
             */
            name: string;
            /**
             * Skip Sso Cache
             * @description Never cache SSO target matches
             * @default false
             */
            skip_sso_cache: boolean;
            /**
             * Verify Ssl
             * @description Verify SSL certs
             * @default true
             */
            verify_ssl: boolean;
        };
        /** UpstreamResyncEnqueue */
        UpstreamResyncEnqueue: {
            /**
             * Kind
             * @description Job kind to run
             * @constant
             */
            kind: "upstream_resync";
            /**
             * Patterns
             * @description Patterns to re-check
             */
            patterns: string[];
            /**
             * Upstream
             * @description Upstream name to resync against
             */
            upstream: string;
        };
        /** UpstreamStats */
        UpstreamStats: {
            /** Cached Entries */
            cached_entries: number;
            /** Configured */
            configured: number;
        };
        /** UpstreamUpdate */
        UpstreamUpdate: {
            /** Base Url */
            base_url?: string | null;
            /** Fail Status Code */
            fail_status_code?: number | null;
            /** Fail Url */
            fail_url?: string | null;
            /** Name */
            name?: string | null;
            /** Skip Sso Cache */
            skip_sso_cache?: boolean | null;
            /** Verify Ssl */
            verify_ssl?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "public" | "unlisted" | "private" | "team";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_backup_archives_api_v1_admin_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRead"][];
                };
            };
        };
    };
    create_backup_job_api_v1_admin_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_backup_api_v1_admin_backup__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_backup_api_v1_admin_backup__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_backup_job_api_v1_admin_backup__name__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_admin_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_config_api_v1_admin_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_auth_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
        };
    };
    issue_api_key_api_v1_auth_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyIssued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_auth_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"] | components["schemas"]["MfaChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    mfa_regenerate_codes_api_v1_auth_mfa_backup_codes_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaRegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_disable_api_v1_auth_mfa_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaDisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_enable_api_v1_auth_mfa_enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaEnableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_setup_api_v1_auth_mfa_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupResponse"];
                };
            };
        };
    };
    mfa_status_api_v1_auth_mfa_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
        };
    };
    mfa_verify_api_v1_auth_mfa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                /** @description Max jobs, newest first */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamResyncEnqueue"] | components["schemas"]["BackupEnqueue"] | components["schemas"]["BackupRestoreEnqueue"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpi_metrics_api_v1_metrics_kpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
        };
    };
    get_live_metrics_api_v1_metrics_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    get_qr_json_api_v1_qr_get: {
        parameters: {
            query: {
                /** @description Shortcut pattern */
                pattern: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_resolve_api_v1_resolve_get: {
        parameters: {
            query: {
                pattern: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shortcuts_api_v1_shortcuts_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                pageSize?: number;
                /** @description Search term across pattern and target */
                q?: string;
                /** @description Filter by tag */
                tag?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortcutListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shortcut_api_v1_shortcuts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShortcutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortcutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_shortcuts_api_v1_shortcuts_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_import_shortcuts_api_v1_shortcuts_bulk_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shortcut_api_v1_shortcuts__pattern__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortcutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shortcut_api_v1_shortcuts__pattern__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shortcut_api_v1_shortcuts__pattern__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShortcutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortcutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_policy_api_v1_site_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePolicy"];
                };
            };
        };
    };
    list_upstreams_api_v1_upstreams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamRead"][];
                };
            };
        };
    };
    create_upstream_api_v1_upstreams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upstream_cache_api_v1_upstreams_cache_get: {
        parameters: {
            query?: {
                /** @description Filter by upstream name */
                upstream?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamCacheEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_upstream_cache_api_v1_upstreams_cache_delete: {
        parameters: {
            query?: {
                /** @description Purge specific upstream only, or all if omitted */
                upstream?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachePurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resync_upstream_cache_api_v1_upstreams_cache_resync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CacheResyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheResyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_cache_entry_api_v1_upstreams_cache__upstream___pattern__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstream: string;
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachePurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_check_logs_api_v1_upstreams_check_logs_get: {
        parameters: {
            query?: {
                /** @description Filter by upstream name */
                upstream?: string | null;
                /** @description Max entries, newest first */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_check_logs_api_v1_upstreams_check_logs_delete: {
        parameters: {
            query?: {
                /** @description Clear one upstream only, or all if omitted */
                upstream?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachePurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_upstream_check_api_v1_upstreams_check_stream__pattern__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upstream_api_v1_upstreams__upstream_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstream_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_upstream_api_v1_upstreams__upstream_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstream_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_qr_image_qr__pattern__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    redirect_shortcut__pattern__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
